In [1]:
import pandas as pd
from sklearn.cluster import DBSCAN
import numpy as np
from sklearn.neighbors import BallTree
import datetime

In [2]:
df = pd.read_csv(r"C:\Users\Jason\Downloads\CMPD_Incidents.csv")
df.head(10)

C:\Users\Jason\AppData\Local\Temp\ipykernel_37252\1129344954.py:1: DtypeWarning: Columns (0: ZIP) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\Jason\Downloads\CMPD_Incidents.csv")

,X,Y,YEAR,INCIDENT_REPORT_ID,LOCATION,CITY,STATE,ZIP,X_COORD_PUBLIC,Y_COORD_PUBLIC,...,LOCATION_TYPE_DESCRIPTION,PLACE_TYPE_DESCRIPTION,PLACE_DETAIL_DESCRIPTION,CLEARANCE_STATUS,CLEARANCE_DETAIL_STATUS,CLEARANCE_DATE,HIGHEST_NIBRS_CODE,HIGHEST_NIBRS_DESCRIPTION,OBJECTID,GlobalID
0,1.402907e+06,498584.000072,2017,20170916-1458-01,16000 PARASOL TREE PL,CHARLOTTE,NC,28278,1402907,498584,...,Indoors,Residential,Apartment/Duplex Private Res,Exceptionally Cleared,Victim Chose not to Prosecute,2017/09/18 00:00:00+00,13C,Intimidation,1,{595CEEB6-71D3-4A3E-BF1F-4D481386F066}
1,1.444906e+06,577199.999992,2024,20240421-1208-01,5200 ELDERBANK DR,CHARLOTTE,NC,NaN,1444906,577200,...,Indoors,Residential,Private Residence,Open,Open,NaN,23H,All Other Thefts,2,{393CDB3C-1BA3-44AA-9116-950908D92EE4}
2,1.479328e+06,532125.999917,2017,20170613-1430-02,5800 EXECUTIVE CENTER DR,CHARLOTTE,NC,28212,1479328,532126,...,Outdoors,Open Area,Street/Highway,Exceptionally Cleared,Cleared by Other Means,2017/07/06 00:00:00+00,899,Other Unlisted Non-Criminal,3,{BC3451B3-2C37-4E8C-B6A7-F41084CB4871}
3,1.439328e+06,519514.999877,2018,20180119-2017-01,5500 SOUTH BV,CHARLOTTE,NC,NaN,1439328,519515,...,Outdoors,Retail,Other - Retail,Open,Open,NaN,290,Damage/Vandalism Of Property,4,{FEE292F9-1FA8-455A-8646-44EE0D336FF0}
4,1.467933e+06,589527.999942,2024,20240620-2218-00,12300 HERITAGE HILLS LN,CHARLOTTE,NC,NaN,1467933,589528,...,Indoors,Residential,Private Residence,Open,"Cleared, Pending Arrest Validation",2024/06/24 00:00:00+00,120,Robbery,5,{B030894A-5A7D-47CA-A715-B953BB5627F1}
5,1.436297e+06,525776.000150,2023,20230710-0206-00,200 W WOODLAWN RD,CHARLOTTE,NC,NaN,1436297,525776,...,Parking Lot,Commercial Place,Other - Commercial Place,Cleared by Arrest,Cleared by Arrest,2023/07/10 00:00:00+00,35A,Drug/Narcotic Violations,6,{C931E015-E318-4E68-9B78-BE151B6B5669}
6,1.496297e+06,577401.999916,2023,20230110-1031-05,4200 AUTUMN FROST TL,CHARLOTTE,NC,28213,1496297,577402,...,Outdoors,Open Area,Construction Site,Open,Open,NaN,23H,All Other Thefts,7,{FC6E5FAD-0CBE-4807-9E6C-EE06B02EFAE6}
7,1.463931e+06,530318.999922,2025,20250916-0909-01,1200 N WENDOVER RD,CHARLOTTE,NC,28211,1463931,530319,...,Indoors,Retail,Other - Retail,Cleared by Arrest by Another Agency,Cleared by Arrest by Another Agency,2025/10/11 00:00:00+00,23C,Shoplifting,8,{20BBC2BD-01F2-4D11-8318-2612EDF65CC8}
8,1.429460e+06,582346.999869,2023,20230513-0944-00,4600 OAKDALE RD,CHARLOTTE,NC,29216,1429460,582347,...,Outdoors,Open Area,Abandoned/Condemned Structure,Open,Open,NaN,90Z,All Other Offenses,9,{5F56FD93-CC8C-4E5A-A2F2-30F458287902}
9,1.479723e+06,519302.999973,2023,20230719-0912-01,7200 E INDEPENDENCE BV,CHARLOTTE,NC,NaN,1479723,519303,...,Parking Lot,Retail,Convenience Store,Open,Open,NaN,280,Stolen Property Offenses,10,{CFBE8BE7-E670-4C94-8185-FA496B3B2927}

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 817714 entries, 0 to 817713
Data columns (total 29 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   X                          817714 non-null  float64
 1   Y                          817714 non-null  float64
 2   YEAR                       817714 non-null  int64
 3   INCIDENT_REPORT_ID         817714 non-null  str
 4   LOCATION                   817714 non-null  str
 5   CITY                       817714 non-null  str
 6   STATE                      817596 non-null  str
 7   ZIP                        540472 non-null  object
 8   X_COORD_PUBLIC             817714 non-null  int64
 9   Y_COORD_PUBLIC             817714 non-null  int64
 10  LATITUDE_PUBLIC            817714 non-null  float64
 11  LONGITUDE_PUBLIC           817714 non-null  float64
 12  DIVISION_ID                817714 non-null  str
 13  CMPD_PATROL_DIVISION       816996 non-null  str
 14  NPA                        817714 non-null  int64
 15  DATE_REPORTED              817714 non-null  str
 16  DATE_INCIDENT_BEGAN        817714 non-null  str
 17  DATE_INCIDENT_END          623528 non-null  str
 18  ADDRESS_DESCRIPTION        817711 non-null  str
 19  LOCATION_TYPE_DESCRIPTION  817714 non-null  str
 20  PLACE_TYPE_DESCRIPTION     817714 non-null  str
 21  PLACE_DETAIL_DESCRIPTION   817714 non-null  str
 22  CLEARANCE_STATUS           817714 non-null  str
 23  CLEARANCE_DETAIL_STATUS    817714 non-null  str
 24  CLEARANCE_DATE             331400 non-null  str
 25  HIGHEST_NIBRS_CODE         817714 non-null  str
 26  HIGHEST_NIBRS_DESCRIPTION  817714 non-null  str
 27  OBJECTID                   817714 non-null  int64
 28  GlobalID                   817714 non-null  str
dtypes: float64(4), int64(5), object(1), str(19)
memory usage: 390.9+ MB

In [4]:
df.isnull().sum()

X                                 0
Y                                 0
YEAR                              0
INCIDENT_REPORT_ID                0
LOCATION                          0
CITY                              0
STATE                           118
ZIP                          277242
X_COORD_PUBLIC                    0
Y_COORD_PUBLIC                    0
LATITUDE_PUBLIC                   0
LONGITUDE_PUBLIC                  0
DIVISION_ID                       0
CMPD_PATROL_DIVISION            718
NPA                               0
DATE_REPORTED                     0
DATE_INCIDENT_BEGAN               0
DATE_INCIDENT_END            194186
ADDRESS_DESCRIPTION               3
LOCATION_TYPE_DESCRIPTION         0
PLACE_TYPE_DESCRIPTION            0
PLACE_DETAIL_DESCRIPTION          0
CLEARANCE_STATUS                  0
CLEARANCE_DETAIL_STATUS           0
CLEARANCE_DATE               486314
HIGHEST_NIBRS_CODE                0
HIGHEST_NIBRS_DESCRIPTION         0
OBJECTID                          0
GlobalID                          0
dtype: int64

In [5]:
df[df.duplicated()]

Empty DataFrame
Columns: [X, Y, YEAR, INCIDENT_REPORT_ID, LOCATION, CITY, STATE, ZIP, X_COORD_PUBLIC, Y_COORD_PUBLIC, LATITUDE_PUBLIC, LONGITUDE_PUBLIC, DIVISION_ID, CMPD_PATROL_DIVISION, NPA, DATE_REPORTED, DATE_INCIDENT_BEGAN, DATE_INCIDENT_END, ADDRESS_DESCRIPTION, LOCATION_TYPE_DESCRIPTION, PLACE_TYPE_DESCRIPTION, PLACE_DETAIL_DESCRIPTION, CLEARANCE_STATUS, CLEARANCE_DETAIL_STATUS, CLEARANCE_DATE, HIGHEST_NIBRS_CODE, HIGHEST_NIBRS_DESCRIPTION, OBJECTID, GlobalID]
Index: []

[0 rows x 29 columns]

In [6]:
df['CITY'].value_counts()

CITY
CHARLOTTE            815988
MECKLENBURG             596
PINEVILLE               305
MATTHEWS                305
HUNTERSVILLE            187
                      ...
CHARLOTTE/NC              1
28215                     1
1640 DEWBERRY TER         1
CHARLOTTE L               1
MATTHES                   1
Name: count, Length: 90, dtype: int64

In [7]:
df["ZIP"] = (
    df["ZIP"]
    .astype(str)
    .str.strip()
    .replace({
        "": pd.NA,
        "NA": pd.NA,
        "N/A": pd.NA,
        "NULL": pd.NA,
        "null": pd.NA,
        "None": pd.NA,
        "00000": pd.NA
    })
)

df["ZIP"] = df["ZIP"].str.extract(r"(\d{5})")[0]

vc = df["ZIP"].value_counts()

df = df[
    df["ZIP"].isna() |      # preserve missing
    (df["ZIP"].map(vc) >= 10)
]
df["ZIP"] = df["ZIP"].astype("category")

In [8]:
df['ZIP'].isna().sum()

np.int64(278162)

In [9]:
df['ZIP'].value_counts()

ZIP
28208    56342
28205    46553
28216    41773
28269    36256
28262    31322
         ...
28083       10
28230       10
28231       10
28286       10
29203       10
Name: count, Length: 122, dtype: int64

In [10]:
# Missing Zip Code Imputation

known_zip = df[df["ZIP"].notna()].copy()
missing_zip = df[df["ZIP"].isna()].copy()
coords = known_zip[["LATITUDE_PUBLIC", "LONGITUDE_PUBLIC"]].to_numpy()

eps = 0.5 / 6371

db = DBSCAN(
    eps=eps,
    min_samples=20,
    metric="haversine"
)

known_zip["cluster"] = db.fit_predict(np.radians(coords))
known_zip = known_zip[known_zip["cluster"] != -1]

cluster_zip_map = (
    known_zip
    .groupby("cluster")["ZIP"]
    .agg(lambda x: x.mode().iloc[0])
)

centroids = (
    known_zip
    .groupby("cluster")[["LATITUDE_PUBLIC", "LONGITUDE_PUBLIC"]]
    .mean()
)

tree = BallTree(
    np.radians(centroids.to_numpy()),
    metric="haversine"
)

dist, idx = tree.query(
    np.radians(missing_zip[["LATITUDE_PUBLIC", "LONGITUDE_PUBLIC"]].to_numpy()),
    k=1
)

# ~1km cutoff
missing_zip["dist_km"] = dist.flatten() * 6371
missing_zip["cluster"] = centroids.index[idx.flatten()]

missing_zip["ZIP"] = missing_zip["cluster"].map(cluster_zip_map)

df = pd.concat([
    known_zip.drop(columns="cluster"),
    missing_zip.drop(columns=["cluster", "dist_km"])
])

In [11]:
df['ZIP'].value_counts()

ZIP
28208    188533
28269     78807
28273     59542
28227     51522
28217     49641
          ...
28286        10
29203        10
28031         5
28036         2
28107         2
Name: count, Length: 122, dtype: int64

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 816099 entries, 0 to 817713
Data columns (total 29 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   X                          816099 non-null  float64
 1   Y                          816099 non-null  float64
 2   YEAR                       816099 non-null  int64
 3   INCIDENT_REPORT_ID         816099 non-null  str
 4   LOCATION                   816099 non-null  str
 5   CITY                       816099 non-null  str
 6   STATE                      815981 non-null  str
 7   ZIP                        816099 non-null  category
 8   X_COORD_PUBLIC             816099 non-null  int64
 9   Y_COORD_PUBLIC             816099 non-null  int64
 10  LATITUDE_PUBLIC            816099 non-null  float64
 11  LONGITUDE_PUBLIC           816099 non-null  float64
 12  DIVISION_ID                816099 non-null  str
 13  CMPD_PATROL_DIVISION       815557 non-null  str
 14  NPA                        816099 non-null  int64
 15  DATE_REPORTED              816099 non-null  str
 16  DATE_INCIDENT_BEGAN        816099 non-null  str
 17  DATE_INCIDENT_END          622249 non-null  str
 18  ADDRESS_DESCRIPTION        816096 non-null  str
 19  LOCATION_TYPE_DESCRIPTION  816099 non-null  str
 20  PLACE_TYPE_DESCRIPTION     816099 non-null  str
 21  PLACE_DETAIL_DESCRIPTION   816099 non-null  str
 22  CLEARANCE_STATUS           816099 non-null  str
 23  CLEARANCE_DETAIL_STATUS    816099 non-null  str
 24  CLEARANCE_DATE             330709 non-null  str
 25  HIGHEST_NIBRS_CODE         816099 non-null  str
 26  HIGHEST_NIBRS_DESCRIPTION  816099 non-null  str
 27  OBJECTID                   816099 non-null  int64
 28  GlobalID                   816099 non-null  str
dtypes: category(1), float64(4), int64(5), str(19)
memory usage: 392.2 MB

In [13]:
df['HIGHEST_NIBRS_DESCRIPTION'].value_counts()

HIGHEST_NIBRS_DESCRIPTION
Theft From Motor Vehicle       82300
All Other Offenses             79434
Other Unlisted Non-Criminal    76812
Simple Assault                 70326
All Other Thefts               69904
                               ...
Welfare Fraud                     11
Betting/Wagering                   9
Purchasing Prostitution            4
Bribery                            3
Gas Leak                           1
Name: count, Length: 72, dtype: int64

In [14]:
df['STATE'].value_counts()

STATE
NC    815973
ND         5
SC         2
IN         1
Name: count, dtype: int64

In [15]:
df['LOCATION_TYPE_DESCRIPTION'].value_counts()

LOCATION_TYPE_DESCRIPTION
Indoors         358030
Outdoors        293394
Parking Lot     127335
Other            24338
Parking Deck     13002
Name: count, dtype: int64

In [16]:
df['PLACE_TYPE_DESCRIPTION'].value_counts()

PLACE_TYPE_DESCRIPTION
Residential               380551
Open Area                 130541
Commercial Place          130264
Retail                    124168
Public/Non-Residential     50575
Name: count, dtype: int64

In [17]:
df['CLEARANCE_STATUS'].value_counts()

CLEARANCE_STATUS
Open                                   492643
Exceptionally Cleared                  160231
Cleared by Arrest                      128391
Unfounded                               27630
Cleared by Arrest by Another Agency      7204
Name: count, dtype: int64

In [18]:
df['YEAR'].value_counts().head(20)

YEAR
2023    95342
2024    92106
2019    91998
2025    91002
2017    90079
2022    89396
2018    88249
2021    84787
2020    83489
2026     9651
Name: count, dtype: int64

In [19]:
def split_incident_datetime(df, col="INCIDENT_REPORT_ID"):

    parts = df[col].str.split("-")

    date_part = parts.str[0]
    time_part = parts.str[1]

    df["date"] = pd.to_datetime(date_part, format="%Y%m%d")
    df["year"] = df["date"].dt.year
    df["hour"] = time_part.str[:2].astype(int)

    df["day_type"] = df["date"].dt.dayofweek.map(
        lambda x: "Saturday" if x == 5 else ("Sunday" if x == 6 else "Weekday")
    )

    return df

In [20]:
year_match = (df['YEAR'] == pd.to_datetime(df['DATE_REPORTED']).dt.year).all()
print(year_match)

True

In [21]:
year_match = (df['YEAR'] == pd.to_datetime(df['DATE_INCIDENT_BEGAN']).dt.year).all()
print(year_match)

False

In [23]:
df_clean = df.drop(columns=['GlobalID', 'X', 'Y', 'STATE', 'X_COORD_PUBLIC', 'Y_COORD_PUBLIC', 'DIVISION_ID', 'DATE_REPORTED', 'CLEARANCE_DATE', 'DATE_INCIDENT_END', 'CITY', 'STATE', 'ADDRESS_DESCRIPTION', 'HIGHEST_NIBRS_CODE', 'CLEARANCE_STATUS', 'CLEARANCE_DETAIL_STATUS', 'OBJECTID', 'DATE_INCIDENT_BEGAN', 'YEAR'])

In [24]:
split_incident_datetime(df_clean)
df_clean.head(25)

,INCIDENT_REPORT_ID,LOCATION,ZIP,LATITUDE_PUBLIC,LONGITUDE_PUBLIC,CMPD_PATROL_DIVISION,NPA,LOCATION_TYPE_DESCRIPTION,PLACE_TYPE_DESCRIPTION,PLACE_DETAIL_DESCRIPTION,HIGHEST_NIBRS_DESCRIPTION,date,year,hour,day_type
0,20170916-1458-01,16000 PARASOL TREE PL,28278,35.103453,-80.996522,Steele Creek,77,Indoors,Residential,Apartment/Duplex Private Res,Intimidation,2017-09-16,2017,14,Saturday
2,20170613-1430-02,5800 EXECUTIVE CENTER DR,28212,35.199555,-80.743016,Hickory Grove,135,Outdoors,Open Area,Street/Highway,Other Unlisted Non-Criminal,2017-06-13,2017,14,Weekday
6,20230110-1031-05,4200 AUTUMN FROST TL,28213,35.324745,-80.688799,University City,155,Outdoors,Open Area,Construction Site,All Other Thefts,2023-01-10,2023,10,Weekday
7,20250916-0909-01,1200 N WENDOVER RD,28211,35.193837,-80.794439,Providence,370,Indoors,Retail,Other - Retail,Shoplifting,2025-09-16,2025,9,Weekday
8,20230513-0944-00,4600 OAKDALE RD,29216,35.334998,-80.913155,North,266,Outdoors,Open Area,Abandoned/Condemned Structure,All Other Offenses,2023-05-13,2023,9,Saturday
10,20170902-2027-02,8900 ALBEMARLE RD,28227,35.210784,-80.697781,Hickory Grove,323,Outdoors,Open Area,Street/Highway,All Other Offenses,2017-09-02,2017,20,Saturday
11,20220528-1038-01,7000 E W T HARRIS BV,28215,35.224880,-80.725711,Hickory Grove,162,Indoors,Retail,Convenience Store,Shoplifting,2022-05-28,2022,10,Saturday
12,20210216-1224-01,1900 TWIN CREEK DR,28262,35.318462,-80.691670,University City,155,Parking Lot,Residential,Apartment/Duplex Private Res,Theft From Motor Vehicle,2021-02-16,2021,12,Weekday
13,20220706-0115-00,3700 THE PLAZA,28205,35.245043,-80.792569,Eastway,10,Outdoors,Residential,Private Residence,All Other Thefts,2022-07-06,2022,1,Weekday
14,20230303-0628-01,8000 NATIONS FORD RD,28217,35.145876,-80.895782,Steele Creek,53,Outdoors,Open Area,Street/Highway,All Other Offenses,2023-03-03,2023,6,Weekday
15,20220704-0820-00,300 S BREVARD ST,28202,35.223007,-80.842269,Central,476,Outdoors,Open Area,Street/Highway,Motor Vehicle Theft,2022-07-04,2022,8,Weekday
16,20190101-1251-00,7100 VILLAGE GREEN DR,28215,35.237587,-80.744828,North Tryon,327,Parking Lot,Residential,Apartment/Duplex Private Res,All Other Offenses,2019-01-01,2019,12,Weekday
20,20170209-1926-00,1900 PATRIOT DR,28227,35.194720,-80.684357,Hickory Grove,145,Parking Lot,Public/Non-Residential,School - Primary or Secondary,Forcible Rape,2017-02-09,2017,19,Weekday
23,20220321-2244-00,1800 WILLOW HAVEN LN,28262,35.336089,-80.719250,University City,336,Outdoors,Residential,Apartment/Duplex Private Res,Burglary/B&E,2022-03-21,2022,22,Weekday
24,20211214-1410-00,1100 JENKINS DR,28212,35.205580,-80.742753,Hickory Grove,127,Outdoors,Residential,Private Residence,Theft From Motor Vehicle,2021-12-14,2021,14,Weekday
25,20190503-1352-02,4800 SPRING LAKE DR,28212,35.223906,-80.747810,Hickory Grove,197,Indoors,Residential,Apartment/Duplex Private Res,Burglary/B&E,2019-05-03,2019,13,Weekday
26,20220303-0708-00,8900 PARK RD,28210,35.112795,-80.857291,South,74,Indoors,Public/Non-Residential,School - Primary or Secondary,Affray,2022-03-03,2022,7,Weekday
27,20201006-2026-00,200 HAWTHORNE LN,28204,35.212899,-80.825598,Providence,367,Indoors,Public/Non-Residential,Hospital/Medical Facility,Other Unlisted Non-Criminal,2020-10-06,2020,20,Weekday
28,20200227-1001-01,7000 WALLACE RD,28202,35.176140,-80.756583,Independence,245,Indoors,Residential,Apartment/Duplex Private Res,Other Unlisted Non-Criminal,2020-02-27,2020,10,Weekday
31,20191221-1256-00,9500 PUDDLE DUCK RD,28262,35.332318,-80.738034,University City,80,Parking Lot,Residential,Private Residence,Motor Vehicle Theft,2019-12-21,2019,12,Saturday
34,20200729-0708-01,14400 CINNAMON FIELD RD,28273,35.099097,-80.972315,Steele Creek,97,Indoors,Residential,Private Residence,Simple Assault,2020-07-29,2020,7,Weekday
35,20220603-1905-01,12500 DEER HOLLOW CT,28273,35.121171,-80.968942,Steele Creek,81,Indoors,Residential,Private Residence,False Pretenses/Swindle,2022-06-03,2022,19,Weekday
36,20251025-2355-00,4000 MONROE RD,28205,35.197472,-80.792487,Providence,366,Parking Lot,Retail,Auto Parts/Service Center,Drug/Narcotic Violations,2025-10-25,2025,23,Saturday
38,20190319-1001-00,5700 GANYMEDE PL,28215,35.215164,-80.701914,Hickory Grove,323,Indoors,Residential,Private Residence,All Other Offenses,2019-03-19,2019,10,Weekday
39,20230519-0638-00,3400 CRAIG AV,28211,35.192742,-80.791733,Providence,394,Parking Lot,Residential,Apartment/Duplex Private Res,Simple Assault,2023-05-19,2023,6,Weekday

In [25]:
df_clean['CMPD_PATROL_DIVISION'].fillna('Unknown', inplace=True)

C:\Users\Jason\AppData\Local\Temp\ipykernel_37252\1276217217.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean['CMPD_PATROL_DIVISION'].fillna('Unknown', inplace=True)

0            Steele Creek
2           Hickory Grove
6         University City
7              Providence
8                   North
               ...
817704       Steele Creek
817705        North Tryon
817706              South
817707            Freedom
817713            Freedom
Name: CMPD_PATROL_DIVISION, Length: 816099, dtype: str

In [26]:
df_clean.isna().sum()

INCIDENT_REPORT_ID             0
LOCATION                       0
ZIP                            0
LATITUDE_PUBLIC                0
LONGITUDE_PUBLIC               0
CMPD_PATROL_DIVISION         542
NPA                            0
LOCATION_TYPE_DESCRIPTION      0
PLACE_TYPE_DESCRIPTION         0
PLACE_DETAIL_DESCRIPTION       0
HIGHEST_NIBRS_DESCRIPTION      0
date                           0
year                           0
hour                           0
day_type                       0
dtype: int64

In [27]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 816099 entries, 0 to 817713
Data columns (total 15 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   INCIDENT_REPORT_ID         816099 non-null  str
 1   LOCATION                   816099 non-null  str
 2   ZIP                        816099 non-null  category
 3   LATITUDE_PUBLIC            816099 non-null  float64
 4   LONGITUDE_PUBLIC           816099 non-null  float64
 5   CMPD_PATROL_DIVISION       815557 non-null  str
 6   NPA                        816099 non-null  int64
 7   LOCATION_TYPE_DESCRIPTION  816099 non-null  str
 8   PLACE_TYPE_DESCRIPTION     816099 non-null  str
 9   PLACE_DETAIL_DESCRIPTION   816099 non-null  str
 10  HIGHEST_NIBRS_DESCRIPTION  816099 non-null  str
 11  date                       816099 non-null  datetime64[us]
 12  year                       816099 non-null  int32
 13  hour                       816099 non-null  int64
 14  day_type                   816099 non-null  str
dtypes: category(1), datetime64[us](1), float64(2), int32(1), int64(2), str(8)
memory usage: 175.7 MB

In [28]:
df_clean.to_csv('data/cmpd_cleaned.csv', index=False)